"""Audit the training corpora. They were generated by scanning docs/books and
templating -- no judgement was applied at construction time, so it has to be
applied now.

    uv run python scripts/corpus/audit_corpora.py
    uv run python scripts/corpus/audit_corpora.py --domain astral --samples 5

WHAT THIS LOOKS FOR, AND WHY EACH ONE HAS ALREADY BITTEN
--------------------------------------------------------
1. ANSWER FORM      Only 9.8% of astral answers contain a runnable uv command,
                    while 50.7% are Python code and 29.4% are pure prose. The
                    adapter then wrote prose when asked for a command. A corpus
                    teaches a FORM, not just facts.
2. DUPLICATION      Template generators repeat. Near-identical records inflate
                    the apparent corpus size and over-weight one phrasing.
3. BOOK ARTIFACTS   Epub-derived text carries "as we saw in Chapter 3",
                    "Figure 4.2", "Listing 2.1" -- references to material the
                    model cannot see, teaching it to make dangling citations.
4. TRUNCATION       Extraction cuts mid-sentence and mid-fence. An unclosed
                    ``` teaches the model to emit unclosed fences.
5. QUESTION FORM    A prompt that only DESCRIBES a situation trains the model to
                    restate it. Same defect that broke the disposition tasks.
6. ANSWER/QUESTION  An answer that ignores its question is noise with a label.
   COHERENCE
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import Counter

from gnn_experiment.canon import REPO_ROOT

MARK = "\n\n### Answer:\n"

CORPORA = {
    "astral": "data/astral/training_data_v4.jsonl",
    "postgresql": "data/postgresql/training_data_v4.jsonl",
    "duckdb": "data/duckdb/training_data_v4.jsonl",
    "financial_planning": "data/financial_planning/training_data_v3.jsonl",
}

# What a RUNNABLE artifact looks like in each domain -- the form the adapter must
# learn to emit, not merely to describe.
RUNNABLE = {
    "astral": r"\b(uv (add|lock|sync|run|init|venv|python|build|pip|tool)|uvx|ruff (check|format))\b",
    "postgresql": r"\b(select|insert|update|delete|create|alter|explain|with)\b[\s\S]{0,400}?\b(from|into|table|index|set)\b",
    "duckdb": r"\b(select|create|attach|install|load|copy|from)\b[\s\S]{0,400}?\b(from|table|'|\")",
    "financial_planning": r"\$[\d,]+|\d+\s*%|\bIRA\b|\b401\(k\)\b",
}

BOOK_ARTIFACTS = [
    (r"\b(?:as (?:we|you) (?:saw|discussed|noted)|earlier in this|in the previous)\b", "backreference"),
    (r"\b(?:Figure|Table|Listing|Example)\s+\d+[.-]\d+", "figure/table citation"),
    (r"\bchapter\s+\d+|\bsection\s+\d+\.\d+", "chapter/section citation"),
    (r"\b(?:see|refer to)\s+(?:page|chapter|section|appendix)\b", "see-also citation"),
    (r"\bthe (?:following|preceding) (?:figure|table|listing|diagram)\b", "dangling pointer"),
]

QUESTION_ASKS = re.compile(
    r"\?|\b(write|give|show|run|make|start|upgrade|count|find|return|insert|"
    r"aggregate|keep|join|get|add|format|check|pull|compute|how|what|why|when|"
    r"explain|describe|implement|create|design|build|convert|optimi[sz]e)\b", re.I)


def split_qa(rec: dict) -> tuple[str, str] | None:
    if "messages" in rec and len(rec["messages"]) >= 2:
        return rec["messages"][0]["content"], rec["messages"][1]["content"]
    t = rec.get("text") or ""
    if MARK in t:
        head, a = t.split(MARK, 1)
        q = head[len("### Question:\n"):] if head.startswith("### Question:\n") else head
        return q, a
    return None


def norm(s: str) -> str:
    """Normalise for near-duplicate detection: identifiers and numbers vary between
    template instances, the SHAPE does not."""
    s = re.sub(r"\d+", "0", s.lower())
    s = re.sub(r"[^a-z0-9\s]", " ", s)
    return " ".join(s.split())


def audit(domain: str, path, samples: int) -> dict:
    rows = [json.loads(l) for l in path.read_text().splitlines() if l.strip()]
    qa = [x for x in (split_qa(r) for r in rows) if x]
    n = len(qa)
    if not n:
        print(f"  {domain}: NO parseable Q/A pairs in {len(rows)} records")
        return {}

    qs = [q for q, _ in qa]
    ans = [a for _, a in qa]
    out: dict = {"records": len(rows), "parsed": n}

    print("=" * 84)
    print(f" {domain}   {len(rows)} records ({n} parsed as Q/A)")
    print("=" * 84)

    fams = Counter(str((r.get("meta") or {}).get("family") or "?") for r in rows)
    top = fams.most_common(5)
    print(f"  families: {len(fams)}   top: " + ", ".join(f"{k}={v}" for k, v in top))
    if top and top[0][1] / len(rows) > 0.25:
        print(f"    ⚠ {top[0][0]} is {top[0][1]/len(rows):.0%} of the corpus")

    # ---- 1. answer form
    run = sum(bool(re.search(RUNNABLE[domain], a, re.I)) for a in ans)
    fence = sum("```" in a for a in ans)
    prose = sum("```" not in a for a in ans)
    print(f"\n  ANSWER FORM")
    print(f"    runnable artifact for this domain   {run*100.0/n:5.1f}%  ({run})")
    print(f"    has any code fence                  {fence*100.0/n:5.1f}%")
    print(f"    pure prose, no code                 {prose*100.0/n:5.1f}%")
    out["runnable_pct"] = run * 100.0 / n

    # ---- 2. duplication
    qd = Counter(hashlib.md5(norm(q).encode()).hexdigest() for q in qs)
    ad = Counter(hashlib.md5(norm(a).encode()).hexdigest() for a in ans)
    qdup = n - len(qd)
    adup = n - len(ad)
    print(f"\n  DUPLICATION (after normalising numbers/identifiers)")
    print(f"    duplicate QUESTIONS  {qdup*100.0/n:5.1f}%  ({qdup})")
    print(f"    duplicate ANSWERS    {adup*100.0/n:5.1f}%  ({adup})")
    out["dup_q_pct"], out["dup_a_pct"] = qdup * 100.0 / n, adup * 100.0 / n

    # ---- 3. book artifacts
    print(f"\n  BOOK ARTIFACTS (references to material the model cannot see)")
    tot_art = 0
    for pat, label in BOOK_ARTIFACTS:
        h = sum(bool(re.search(pat, a, re.I)) for a in ans)
        tot_art += h
        if h:
            print(f"    {label:26s} {h*100.0/n:5.1f}%  ({h})")
    if not tot_art:
        print("    none")
    out["artifact_hits"] = tot_art

    # ---- 4. truncation / malformed
    unclosed = sum(a.count("```") % 2 for a in ans)
    midsent = sum(bool(re.search(r"[a-z,]\s*$", a.strip())) for a in ans)
    print(f"\n  TRUNCATION / MALFORMED")
    print(f"    unclosed code fence   {unclosed*100.0/n:5.1f}%  ({unclosed})")
    print(f"    ends mid-sentence     {midsent*100.0/n:5.1f}%  ({midsent})")
    out["unclosed_pct"] = unclosed * 100.0 / n

    # ---- 5. question form
    noask = sum(not QUESTION_ASKS.search(q) for q in qs)
    print(f"\n  QUESTION FORM")
    print(f"    requests no action (model can restate)  {noask*100.0/n:5.1f}%  ({noask})")
    ql = sorted(len(q) for q in qs)
    al = sorted(len(a) for a in ans)
    print(f"    question chars  median {ql[n//2]:5d}  p95 {ql[int(n*.95)]:6d}")
    print(f"    answer   chars  median {al[n//2]:5d}  p95 {al[int(n*.95)]:6d}")
    out["noask_pct"] = noask * 100.0 / n

    # ---- 6. coherence: does the answer share content words with its question?
    weak = 0
    for q, a in qa:
        qw = {w for w in norm(q).split() if len(w) > 4}
        aw = {w for w in norm(a).split() if len(w) > 4}
        if qw and len(qw & aw) / len(qw) < 0.10:
            weak += 1
    print(f"\n  Q/A COHERENCE")
    print(f"    answer shares <10% of question's content words  {weak*100.0/n:5.1f}%  ({weak})")
    out["incoherent_pct"] = weak * 100.0 / n

    if samples:
        print(f"\n  SAMPLES")
        for q, a in qa[:samples]:
            print(f"    Q: {q[:110].strip()}")
            print(f"    A: {a[:110].strip()}\n")
    print()
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--domain", choices=list(CORPORA))
    ap.add_argument("--samples", type=int, default=0)
    args = ap.parse_args()

    doms = [args.domain] if args.domain else list(CORPORA)
    summary = {}
    for d in doms:
        p = REPO_ROOT / CORPORA[d]
        if not p.exists():
            print(f"  {d}: MISSING {p}")
            continue
        summary[d] = audit(d, p, args.samples)

    print("=" * 84)
    print(f" {'domain':20s} {'runnable':>9s} {'dupQ':>7s} {'dupA':>7s} {'noask':>7s} "
          f"{'unclosed':>9s} {'incoh':>7s}")
    print("-" * 84)
    for d, s in summary.items():
        if s:
            print(f" {d:20s} {s['runnable_pct']:8.1f}% {s['dup_q_pct']:6.1f}% "
                  f"{s['dup_a_pct']:6.1f}% {s['noask_pct']:6.1f}% "
                  f"{s['unclosed_pct']:8.1f}% {s['incoherent_pct']:6.1f}%")
    print("=" * 84)


if __name__ == "__main__":
    main()
